package _13_roomtype.model;
// Generated 2016/1/21 �U�� 01:39:27 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import org.hibernate.Session;

import _10_package.model.PackageVO;
import _11_room.model.RoomVO;
import _12_roompic.model.RoomPicVO;
import hibernate.util.HibernateUtil;

/**
 * RoomType generated by hbm2java
 */
public class RoomTypeVO implements java.io.Serializable {

	private Integer roomType_id;
	private String room_type;
	private Integer rtCapacity_num;
	private Integer rtCount;
	private Integer rtWeekday_rate;
	private Integer rtWeekend_rate;
	private Set<RoomVO> rooms = new HashSet<RoomVO>(0);
	private Set<PackageVO> packages = new HashSet<PackageVO>(0);
	private Set<RoomPicVO> roomPics = new HashSet<RoomPicVO>(0);
	
//	public static void main(String []args){
//		
//		Session session=HibernateUtil.getSessionFactory().getCurrentSession();
//		session.beginTransaction();
//		
//		RoomTypeVO packageBean=(RoomTypeVO)session.get(RoomTypeVO.class,1 );
//		System.out.println(packageBean);
//		
//		session.getTransaction().commit();
//		
//		}

	@Override
	public String toString() {
		return "RoomTypeVO [roomType_id=" + roomType_id + ", room_type=" + room_type + ", rtCapacity_num="
				+ rtCapacity_num + ", rtCount=" + rtCount + ", rtWeekday_rate=" + rtWeekday_rate + ", rtWeekend_rate="
				+ rtWeekend_rate + ", rooms=" + rooms.size() + ", packages=" + packages.size() + ", roomPics=" + roomPics.size() + "]";
	}

	public Integer getRoomType_id() {
		return roomType_id;
	}

	public void setRoomType_id(Integer roomType_id) {
		this.roomType_id = roomType_id;
	}

	public String getRoom_type() {
		return room_type;
	}

	public void setRoom_type(String room_type) {
		this.room_type = room_type;
	}

	public Integer getRtCapacity_num() {
		return rtCapacity_num;
	}

	public void setRtCapacity_num(Integer rtCapacity_num) {
		this.rtCapacity_num = rtCapacity_num;
	}

	public Integer getRtCount() {
		return rtCount;
	}

	public void setRtCount(Integer rtCount) {
		this.rtCount = rtCount;
	}

	public Integer getRtWeekday_rate() {
		return rtWeekday_rate;
	}

	public void setRtWeekday_rate(Integer rtWeekday_rate) {
		this.rtWeekday_rate = rtWeekday_rate;
	}

	public Integer getRtWeekend_rate() {
		return rtWeekend_rate;
	}

	public void setRtWeekend_rate(Integer rtWeekend_rate) {
		this.rtWeekend_rate = rtWeekend_rate;
	}

	public Set<RoomVO> getRooms() {
		return rooms;
	}

	public void setRooms(Set<RoomVO> rooms) {
		this.rooms = rooms;
	}

	public Set<PackageVO> getPackages() {
		return packages;
	}

	public void setPackages(Set<PackageVO> packages) {
		this.packages = packages;
	}

	public Set<RoomPicVO> getRoomPics() {
		return roomPics;
	}

	public void setRoomPics(Set<RoomPicVO> roomPics) {
		this.roomPics = roomPics;
	}
	


}
